# Generated by Django 5.2 on 2026-09-26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0004_patient_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_for", models.DateTimeField(verbose_name="fecha y hora")),
                ("visit_type", models.CharField(choices=[("clinical", "Consulta clínica"), ("vaccination", "Vacunación"), ("delivery", "Entrega de productos"), ("follow_up", "Control o seguimiento"), ("other", "Otro")], default="clinical", max_length=20, verbose_name="tipo de visita")),
                ("status", models.CharField(choices=[("requested", "Solicitada"), ("confirmed", "Confirmada"), ("on_route", "En camino"), ("completed", "Finalizada"), ("canceled", "Cancelada")], default="requested", max_length=16, verbose_name="estado")),
                ("address", models.CharField(max_length=180, verbose_name="dirección")),
                ("zone", models.CharField(blank=True, max_length=100, verbose_name="zona o barrio")),
                ("reason", models.CharField(max_length=180, verbose_name="motivo")),
                ("notes", models.TextField(blank=True, verbose_name="observaciones")),
                ("price", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0"))], verbose_name="valor sugerido")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="home_visits", to=settings.AUTH_USER_MODEL, verbose_name="profesional asignado")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="home_visits", to="patients.patient", verbose_name="paciente")),
            ],
            options={"verbose_name": "visita a domicilio", "verbose_name_plural": "visitas a domicilio", "ordering": ["scheduled_for", "id"]},
        ),
    ]
