# Generated by Django 5.2.16 on 2026-07-30 01:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='código interno')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('category', models.CharField(choices=[('food', 'Alimento'), ('toy', 'Juguete'), ('clothing', 'Abrigo y ropa'), ('bed', 'Cama y descanso'), ('accessory', 'Accesorio'), ('hygiene', 'Higiene'), ('other', 'Otro')], max_length=16, verbose_name='categoría')),
                ('sale_unit', models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('bag', 'Bolsa')], default='unit', max_length=8, verbose_name='se vende por')),
                ('package_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='peso de bolsa (kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio habitual')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio promocional')),
                ('promotion_starts_on', models.DateField(blank=True, null=True, verbose_name='promoción desde')),
                ('promotion_ends_on', models.DateField(blank=True, null=True, verbose_name='promoción hasta')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='stock actual')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='stock mínimo')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.brand', verbose_name='marca')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
            },
        ),
    ]
