# Generated by Django 5.2.16 on 2026-07-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(blank=True, max_length=80, verbose_name='calidad o línea'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_visit_on',
            field=models.DateField(blank=True, null=True, verbose_name='última visita'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='visit_frequency',
            field=models.CharField(choices=[('daily', 'Todos los días'), ('weekly', 'Una vez por semana'), ('twice_weekly', 'Dos veces por semana'), ('as_needed', 'A demanda')], default='as_needed', max_length=16, verbose_name='frecuencia de visita'),
        ),
    ]
