# Generated by Django 5.2.16 on 2026-07-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_quality_supplier_last_visit_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.CharField(blank=True, max_length=80, verbose_name='lote'),
        ),
        migrations.AddField(
            model_name='product',
            name='expires_on',
            field=models.DateField(blank=True, null=True, verbose_name='vencimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='requiere receta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Alimento'), ('toy', 'Juguete'), ('clothing', 'Abrigo y ropa'), ('bed', 'Cama y descanso'), ('accessory', 'Accesorio'), ('hygiene', 'Higiene'), ('shampoo', 'Shampoo y cosmética'), ('medicine', 'Medicamento veterinario'), ('antiparasitic', 'Pipeta y antiparasitario'), ('other', 'Otro')], max_length=16, verbose_name='categoría'),
        ),
    ]
