# Generated by Django 5.1.15 on 2026-07-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('veterinary', 'Veterinaria'), ('shelter', 'Refugio o perrera')], max_length=20, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
            },
        ),
    ]
