# Generated by Django 5.2.16 on 2026-07-29 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroomingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(editable=False)),
                ('status', models.CharField(choices=[('booked', 'Reservado'), ('confirmed', 'Confirmado'), ('done', 'Finalizado'), ('canceled', 'Cancelado')], default='booked', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grooming_appointments', to='patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grooming.groomingservice')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
