# Generated by Django 5.2.16 on 2026-07-30 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0001_initial'),
        ('patients', '0003_patient_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groomingappointment',
            options={'ordering': ['starts_at'], 'verbose_name': 'turno de peluquería', 'verbose_name_plural': 'turnos de peluquería'},
        ),
        migrations.AlterModelOptions(
            name='groomingservice',
            options={'verbose_name': 'servicio de peluquería', 'verbose_name_plural': 'servicios de peluquería'},
        ),
        migrations.AlterField(
            model_name='groomingappointment',
            name='ends_at',
            field=models.DateTimeField(editable=False, verbose_name='finaliza'),
        ),
        migrations.AlterField(
            model_name='groomingappointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='groomingappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grooming_appointments', to='patients.patient', verbose_name='paciente'),
        ),
        migrations.AlterField(
            model_name='groomingappointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grooming.groomingservice', verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='groomingappointment',
            name='starts_at',
            field=models.DateTimeField(verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='groomingappointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Reservado'), ('confirmed', 'Confirmado'), ('done', 'Finalizado'), ('canceled', 'Cancelado')], default='booked', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='groomingservice',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='groomingservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='duración en minutos'),
        ),
        migrations.AlterField(
            model_name='groomingservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
