# Generated by Django 5.2.16 on 2026-07-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0002_alter_groomingappointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomingappointment',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='additional_appointments', to='grooming.groomingservice', verbose_name='servicios adicionales'),
        ),
    ]
