# Generated by Django 5.1.15 on 2026-07-29 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='nombre completo o razón social')),
                ('kind', models.CharField(choices=[('person', 'Persona'), ('institution', 'Institución')], default='person', max_length=16, verbose_name='tipo')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otra')], max_length=12, verbose_name='especie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='raza')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('microchip', models.CharField(blank=True, max_length=80, verbose_name='microchip o identificación')),
                ('allergies', models.TextField(blank=True, verbose_name='alergias')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('responsible', 'Responsable'), ('adopter', 'Adoptante'), ('custodian', 'Cuidador')], max_length=16, verbose_name='vínculo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='contacto principal')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.contact')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='contacts',
            field=models.ManyToManyField(related_name='patients', through='patients.PatientContact', to='patients.contact'),
        ),
        migrations.AddConstraint(
            model_name='patientcontact',
            constraint=models.UniqueConstraint(fields=('patient', 'contact', 'role'), name='unique_patient_contact_role'),
        ),
    ]
