# Generated by Django 5.2.16 on 2026-07-29 23:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('reason', models.CharField(max_length=180, verbose_name='motivo de consulta')),
                ('notes', models.TextField(verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro clínico',
                'verbose_name_plural': 'registros clínicos',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
    ]
