# Generated by Django 5.2.16 on 2026-07-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_clinicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, upload_to='patients/%Y/%m/', verbose_name='foto'),
        ),
    ]
