# Generated by Django 5.2.16 on 2026-07-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
