# Generated by Django 5.2 on 2026-09-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("patients", "0004_patient_active")]

    operations = [
        migrations.CreateModel(
            name="CareReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("vaccine", "Vacuna"), ("antiparasitic", "Antiparasitario"), ("clinical_control", "Control clínico"), ("medication", "Medicación"), ("other", "Otro")], max_length=20, verbose_name="tipo")),
                ("due_on", models.DateField(verbose_name="fecha prevista")),
                ("notes", models.CharField(blank=True, max_length=180, verbose_name="detalle")),
                ("completed_on", models.DateField(blank=True, null=True, verbose_name="realizado el")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="care_reminders", to="patients.patient", verbose_name="paciente")),
            ],
            options={"verbose_name": "recordatorio de cuidado", "verbose_name_plural": "recordatorios de cuidado", "ordering": ["due_on", "id"]},
        ),
    ]
