# Generated by Django 5.2 on 2026-10-05

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0005_carereminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostPetReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="nombre del animal")),
                ("species", models.CharField(choices=[("dog", "Perro"), ("cat", "Gato"), ("other", "Otra")], max_length=12, verbose_name="especie")),
                ("breed", models.CharField(blank=True, max_length=100, verbose_name="raza")),
                ("description", models.TextField(blank=True, verbose_name="señas particulares")),
                ("photo", models.ImageField(blank=True, upload_to="lost-pets/%Y/%m/", verbose_name="foto")),
                ("last_seen_at", models.DateTimeField(verbose_name="última vez visto")),
                ("area_label", models.CharField(max_length=120, verbose_name="zona o barrio")),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[MinValueValidator(Decimal("-90")), MaxValueValidator(Decimal("90"))], verbose_name="latitud exacta")),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[MinValueValidator(Decimal("-180")), MaxValueValidator(Decimal("180"))], verbose_name="longitud exacta")),
                ("status", models.CharField(choices=[("published", "Publicado"), ("hidden", "Oculto"), ("resolved", "Resuelto"), ("archived", "Archivado")], default="published", max_length=16, verbose_name="estado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lost_pet_reports", to="patients.patient", verbose_name="paciente vinculado")),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lost_pet_reports", to=settings.AUTH_USER_MODEL, verbose_name="creado por")),
            ],
            options={"verbose_name": "aviso de animal extraviado", "verbose_name_plural": "avisos de animales extraviados", "ordering": ["status", "-last_seen_at", "-id"]},
        ),
        migrations.CreateModel(
            name="Sighting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seen_at", models.DateTimeField(default=timezone.now, verbose_name="fecha y hora del avistamiento")),
                ("area_label", models.CharField(max_length=120, verbose_name="zona o barrio")),
                ("description", models.TextField(blank=True, verbose_name="detalle del avistamiento")),
                ("photo", models.ImageField(blank=True, upload_to="lost-pets/sightings/%Y/%m/", verbose_name="foto")),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[MinValueValidator(Decimal("-90")), MaxValueValidator(Decimal("90"))], verbose_name="latitud exacta")),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[MinValueValidator(Decimal("-180")), MaxValueValidator(Decimal("180"))], verbose_name="longitud exacta")),
                ("status", models.CharField(choices=[("published", "Publicado"), ("hidden", "Oculto")], default="published", max_length=16, verbose_name="estado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sightings", to="lost_pets.lostpetreport", verbose_name="aviso")),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lost_pet_sightings", to=settings.AUTH_USER_MODEL, verbose_name="reportado por")),
            ],
            options={"verbose_name": "avistamiento", "verbose_name_plural": "avistamientos", "ordering": ["-seen_at", "-id"]},
        ),
    ]
